name: xcodebuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: .cache
        key: ${{ runner.os }}-spm-v2-${{ hashFiles('**/Package.resolved') }}
        restore-keys: ${{ runner.os }}-spm-v2-
    - name: Build
      run:  xcodebuild -scheme "iOS"  -clonedSourcePackagesDirPath .cache -destination "platform=iOS Simulator,name=iPhone 11 Pro"
