name: xcodebuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: .cache
        key: ${{ runner.os }}-spm-v2-${{ hashFiles('**/Package.resolved') }}
        restore-keys: ${{ runner.os }}-spm-v2-
    - name: Build iOS
      run:  xcodebuild -scheme "iOS"  -clonedSourcePackagesDirPath .cache -destination "generic/platform=iOS"
    - name: Build macOS
      run:  xcodebuild -scheme "macOS"  -clonedSourcePackagesDirPath .cache -destination "generic/platform=macOS"
    - name: Build Safari
      run:  xcodebuild -scheme "iOS"  -clonedSourcePackagesDirPath .cache -destination "generic/platform=macOS"
    - name: Build watchOS
      run:  xcodebuild -scheme "Watch"  -clonedSourcePackagesDirPath .cache -destination "generic/platform=watchOS"
